### ISSUE TITLE
Cannot read property 'split' of undefined?

### ISSUE THREAD

**Issue by luke-nelson2** [kevinfaveri/solana-candy-factory#34]
```
yarn run v1.22.15
$ yarn setup-solana-dev && yarn setup-metaplex-dev && yarn setup-envs-dev
$ ./devtools/dev/setup-solana-dev.sh
$ node ./devtools/dev/setup-metaplex-dev.js
Type mint price [default 1 sol]:
Type start date of the minting [default 16 Sep 2021 00:00:00]:
'sh' is not recognized as an internal or external command,
operable program or batch file.
$ node ./devtools/dev/setup-envs-dev.js
C:\Users\nelso\Documents\candy factory\solana-candy-factory\devtools\dev\setup-envs-dev.js:33
      NEXT_PUBLIC_TREASURY_ADDRESS = fileContent.toString().split('\n')[4].split(' ')[1].trim();
                                                                          ^

TypeError: Cannot read property 'split' of undefined
    at C:\Users\nelso\Documents\candy factory\solana-candy-factory\devtools\dev\setup-envs-dev.js:33:75
    at Array.forEach (<anonymous>)
    at C:\Users\nelso\Documents\candy factory\solana-candy-factory\devtools\dev\setup-envs-dev.js:13:9
    at FSReqCallback.oncomplete (fs.js:179:23)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I am getting this error when I finally run the yarn setup-dev command, and it says that fileContent.toString().split('\n')[4] is undefined. I can't seem to figure out what is wrong.

**Comment by kevinfaveri** [comment]
Hey bro! The repo and scripts have been updated.
Please clone the updated version and test again. If the issue remains, reopen the issue with your codebase so I can validate what is happening.
