### ISSUE TITLE
yarn setup-dev ~> "A has_one constraint was violated"

### ISSUE THREAD

**Issue by ZEAL-MATCH-LTD** [kevinfaveri/solana-candy-factory#35]
Hello again!
I am trying to upload 100 assets to devnet and after a few minutes wait and what looks like a positive upload then spits out a constant never-ending stream of errors (see below)

I've pulled latest on metaplex and run `yarn bootstrap`

Are you seeing this issue your end? 
My file names are incrementing numbers e.g 0.png, 1.png etc...

```ruby
Transaction simulation failed: Error processing Instruction 0: custom program error: 0x8d 
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]
    Program log: Custom program error: 0x8d
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 16007 of 200000 compute units
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x8d
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x8d
    at Connection.sendEncodedTransaction (/Users/[redacted]/metaplex-foundation/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:3553:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Connection.sendRawTransaction (/Users/[redacted]/metaplex-foundation/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:3513:20)
    at async Object.sendAndConfirmRawTransaction (/Users/[redacted]/metaplex-foundation/metaplex/js/node_modules/@solana/web3.js/src/util/send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (/Users/[redacted]/metaplex-foundation/metaplex/js/node_modules/@project-serum/anchor/src/provider.ts:112:18)
    at async Object.rpc [as addConfigLines] (/Users/[redacted]/metaplex-foundation/metaplex/js/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:19:23) {
  logs: [
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]',
    'Program log: Custom program error: 0x8d',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 16007 of 200000 compute units',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x8d'
  ]
}
saving config line 0-9 failed ProgramError: 
    at Function.parse (/Users/[redacted]/metaplex-foundation/metaplex/js/node_modules/@project-serum/anchor/src/error.ts:36:14)
    at Object.rpc [as addConfigLines] (/Users/[redacted]/metaplex-foundation/metaplex/js/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:23:42)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 141,
  msg: 'A has_one constraint was violated'
}
Writing indices 10-19
```
### 0.json example
```json
{
    "name": "OG_SLOG#1",
    "symbol": "[REDACTED]",
    "seller_fee_basis_points": 500,
    "image": "0.png",
    "attributes": {
        "Primary Color": "Green",
        "Secondary Color": "Purple",
        "Skin Pattern": "Swirl_Large",
        "Eye Pattern": "Eye_Pattern_B",
        "Pupil Pattern": "Pupil_Pattern_A",
        "Skin Bumpy": "0.5",
        "Metalic A": "0.25",
        "Metalic B": "0.5",
        "Roughness A": "0.25",
        "Roughness B": "0.1",
        "Primary Shade": "9.0",
        "Secondary Shade": "11.0"
    },
    "properties": {
        "creators": [{
            "address": "[REDACTED]",
            "share": 100
        }],
        "files": [{
            "uri": "0.png",
            "type": "image/png"
        }]
    }
}
```

**Comment by andiradulescu** [comment]
Try reverting this commit https://github.com/kevinfaveri/solana-candy-factory/commit/05d420d20bc9c91e6a1fb3ba3637b2e50342ef49 (not sure why this change was made @kevinfaveri, maybe you can explain) or better just delete the `devnet-temp` file inside the `.cache` folder in the root of the project, **every-time, before running** `yarn setup-dev`.

In the README it says that:
- You should have all your NFTs ready before deploying. Incremental deploying of NFTs is not supported right now.

Hope this helps!
