### ISSUE TITLE
yarn dev - INVALID URL

### ISSUE THREAD

**Issue by Tarnn** [kevinfaveri/solana-candy-factory#38]
Getting INVALID_URL when I go to localhost:3000

![image](https://user-images.githubusercontent.com/12399112/137238810-8eac34b5-5ea8-4d71-ab27-bb31e40c529b.png)

$ yarn dev
yarn run v1.22.15
$ next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
event - compiled successfully
event - build page: /
wait  - compiling...
event - compiled successfully
event - build page: /next/dist/pages/_error
wait  - compiling...
event - compiled successfully
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:371:5)
    at onParseError (node:internal/url:552:9)
    at new URL (node:internal/url:628:5)
    at new Connection (C:\Users\Tarnnn\OneDrive\Desktop\sol-candy\solana-candy-factory\node_modules\@solana\web3.js\lib\index.cjs.js:3504:15)
    at Object../src/hooks/use-wallet-balance.tsx (C:\Users\Tarnnn\OneDrive\Desktop\sol-candy\solana-candy-factory\.next\server\pages\_app.js:37:20)
    at __webpack_require__ (C:\Users\Tarnnn\OneDrive\Desktop\sol-candy\solana-candy-factory\.next\server\webpack-runtime.js:25:42)
    at Object../src/pages/_app.tsx (C:\Users\Tarnnn\OneDrive\Desktop\sol-candy\solana-candy-factory\.next\server\pages\_app.js:104:83)
    at __webpack_require__ (C:\Users\Tarnnn\OneDrive\Desktop\sol-candy\solana-candy-factory\.next\server\webpack-runtime.js:25:42)
    at __webpack_exec__ (C:\Users\Tarnnn\OneDrive\Desktop\sol-candy\solana-candy-factory\.next\server\pages\_app.js:275:39)
    at C:\Users\Tarnnn\OneDrive\Desktop\sol-candy\solana-candy-factory\.next\server\pages\_app.js:276:28 {
  input: 'undefined',
  code: 'ERR_INVALID_URL'
}
error - TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:371:5)
    at onParseError (node:internal/url:552:9)
    at new URL (node:internal/url:628:5)
    at new Connection (C:\Users\Tarnnn\OneDrive\Desktop\sol-candy\solana-candy-factory\node_modules\@solana\web3.js\lib\index.cjs.js:3504:15)
    at Object../src/hooks/use-wallet-balance.tsx (C:\Users\Tarnnn\OneDrive\Desktop\sol-candy\solana-candy-factory\.next\server\pages\_app.js:37:20)
    at __webpack_require__ (C:\Users\Tarnnn\OneDrive\Desktop\sol-candy\solana-candy-factory\.next\server\webpack-runtime.js:25:42)
    at Object../src/pages/_app.tsx (C:\Users\Tarnnn\OneDrive\Desktop\sol-candy\solana-candy-factory\.next\server\pages\_app.js:104:83)
    at __webpack_require__ (C:\Users\Tarnnn\OneDrive\Desktop\sol-candy\solana-candy-factory\.next\server\webpack-runtime.js:25:42)
    at __webpack_exec__ (C:\Users\Tarnnn\OneDrive\Desktop\sol-candy\solana-candy-factory\.next\server\pages\_app.js:275:39)
    at C:\Users\Tarnnn\OneDrive\Desktop\sol-candy\solana-candy-factory\.next\server\pages\_app.js:276:28 {
  input: 'undefined',
  code: 'ERR_INVALID_URL',
  page: '/'
}
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:371:5)
    at onParseError (node:internal/url:552:9)
    at new URL (node:internal/url:628:5)
    at new Connection (C:\Users\Tarnnn\OneDrive\Desktop\sol-candy\solana-candy-factory\node_modules\@solana\web3.js\lib\index.cjs.js:3504:15)
    at Object../src/hooks/use-wallet-balance.tsx (C:\Users\Tarnnn\OneDrive\Desktop\sol-candy\solana-candy-factory\.next\server\pages\_app.js:37:20)
    at __webpack_require__ (C:\Users\Tarnnn\OneDrive\Desktop\sol-candy\solana-candy-factory\.next\server\webpack-runtime.js:25:42)
    at Object../src/pages/_app.tsx (C:\Users\Tarnnn\OneDrive\Desktop\sol-candy\solana-candy-factory\.next\server\pages\_app.js:104:83)
    at __webpack_require__ (C:\Users\Tarnnn\OneDrive\Desktop\sol-candy\solana-candy-factory\.next\server\webpack-runtime.js:25:42)
    at __webpack_exec__ (C:\Users\Tarnnn\OneDrive\Desktop\sol-candy\solana-candy-factory\.next\server\pages\_app.js:275:39)
    at C:\Users\Tarnnn\OneDrive\Desktop\sol-candy\solana-candy-factory\.next\server\pages\_app.js:276:28 {
  input: 'undefined',
  code: 'ERR_INVALID_URL'
}

**Comment by kevinfaveri** [comment]
Also, please try again with the updated repo. The NFT Manager has been completely removed, and other tools for generating the sources have been suggested. If the problem persists, please reopen: https://github.com/kevinfaveri/solana-candy-factory#others-tools
