### ISSUE TITLE
Yarn build not working

### ISSUE THREAD

**Issue by advanztek** [kevinfaveri/solana-candy-factory#57]
Yarn build always display this errors

 yarn build
yarn run v1.22.5
$ next build
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types

./src/pages/index.tsx
33:9  Warning: Do not use <img>. Use Image from 'next/image' instead. See https://nextjs.org/docs/messages/no-img-element.  @next/next/no-img-element

./src/pages/my-nfts.tsx
37:15  Warning: Do not use <img>. Use Image from 'next/image' instead. See https://nextjs.org/docs/messages/no-img-element.  @next/next/no-img-element

./src/components/recaptcha-button.tsx
34:6  Warning: React Hook useCallback has missing dependencies: 'actionName', 'executeRecaptcha', and 'onClick'. Either include them or remove the dependency array. If 'onC
lick' changes too often, find the parent component that defines it and wrap that definition in useCallback.  react-hooks/exhaustive-deps

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
info  - Creating an optimized production build
info  - Compiled successfully

> Build error occurred
TypeError [ERR_INVALID_URL]: Invalid URL: undefined
    at onParseError (internal/url.js:279:9)
    at new URL (internal/url.js:355:5)
    at new Connection (C:\Users\user\ssscc\solana-candy-factory\node_modules\@project-serum\anchor\node_modules\@solana\web3.js\lib\index.cjs.js:3472:15)
    at Object.3924 (C:\Users\user\ssscc\solana-candy-factory\.next\server\chunks\924.js:29:20)
    at __webpack_require__ (C:\Users\user\ssscc\solana-candy-factory\.next\server\webpack-runtime.js:25:42)
    at Object.9064 (C:\Users\user\ssscc\solana-candy-factory\.next\server\pages\_app.js:21:83)
    at __webpack_require__ (C:\Users\user\ssscc\solana-candy-factory\.next\server\webpack-runtime.js:25:42)
    at __webpack_exec__ (C:\Users\user\ssscc\solana-candy-factory\.next\server\pages\_app.js:155:39)
    at C:\Users\user\ssscc\solana-candy-factory\.next\server\pages\_app.js:156:70
    at Function.__webpack_require__.X (C:\Users\user\ssscc\solana-candy-factory\.next\server\webpack-runtime.js:108:21) {
  type: 'NodeError',
  input: 'undefined',
  code: 'ERR_INVALID_URL'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by leclicinformatique** [comment]
Same problem for me

**Comment by kevinfaveri** [comment]
You need to have a .env file ready otherwise it will not build.
