### ISSUE TITLE
saving config line 10-19 failed RangeError: encoding overruns Buffer

### ISSUE THREAD

**Issue by splunkmeta** [kevinfaveri/solana-candy-factory#58]
ts-node F:\MINT100NFT\metaplex\js\packages\cli\src\candy-machine-cli.ts upload ./assets --env mainnet-beta --keypair F:\MINT100NFT\metaplex\~\config\solana\mainnet-beta.json
Beginning the upload for 101 (png+json) pairs
started at: 1636354950296
wallet public key: 7xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Processing file: 0
Processing file: 50
Processing file: 100
Processing file: 150
Processing file: 200
Writing indices 10-19
saving config line 10-19 failed RangeError: encoding overruns Buffer
    at Blob.encode (F:\MINT100NFT\metaplex\js\node_modules\buffer-layout\lib\Layout.js:2334:13)
    at Structure.encode (F:\MINT100NFT\metaplex\js\node_modules\buffer-layout\lib\Layout.js:1272:26)
    at WrappedLayout.encode (F:\MINT100NFT\metaplex\js\node_modules\@project-serum\borsh\src\index.ts:96:24)
    at WrappedLayout.encode (F:\MINT100NFT\metaplex\js\node_modules\@project-serum\borsh\src\index.ts:96:24)
    at Structure.encode (F:\MINT100NFT\metaplex\js\node_modules\buffer-layout\lib\Layout.js:1272:26)
    at F:\MINT100NFT\metaplex\js\node_modules\buffer-layout\lib\Layout.js:1117:25
    at Array.reduce (<anonymous>)
    at Sequence.encode (F:\MINT100NFT\metaplex\js\node_modules\buffer-layout\lib\Layout.js:1116:22)
    at Structure.encode (F:\MINT100NFT\metaplex\js\node_modules\buffer-layout\lib\Layout.js:1272:26)
    at WrappedLayout.encode (F:\MINT100NFT\metaplex\js\node_modules\@project-serum\borsh\src\index.ts:96:24)
Writing indices 20-29
saving config line 20-29 failed RangeError: encoding overruns Buffer
    at Blob.encode (F:\MINT100NFT\metaplex\js\node_modules\buffer-layout\lib\Layout.js:2334:13)
    at Structure.encode (F:\MINT100NFT\metaplex\js\node_modules\buffer-layout\lib\Layout.js:1272:26)
    at WrappedLayout.encode (F:\MINT100NFT\metaplex\js\node_modules\@project-serum\borsh\src\index.ts:96:24)
    at WrappedLayout.encode (F:\MINT100NFT\metaplex\js\node_modules\@project-serum\borsh\src\index.ts:96:24)
    at Structure.encode (F:\MINT100NFT\metaplex\js\node_modules\buffer-layout\lib\Layout.js:1272:26)
    at F:\MINT100NFT\metaplex\js\node_modules\buffer-layout\lib\Layout.js:1117:25
    at Array.reduce (<anonymous>)
    at Sequence.encode (F:\MINT100NFT\metaplex\js\node_modules\buffer-layout\lib\Layout.js:1116:22)
    at Structure.encode (F:\MINT100NFT\metaplex\js\node_modules\buffer-layout\lib\Layout.js:1272:26)
    at WrappedLayout.encode (F:\MINT100NFT\metaplex\js\node_modules\@project-serum\borsh\src\index.ts:96:24)

**Comment by kevinfaveri** [comment]
Your nft name is too long. Fix it and upload again and it should work.
