### ISSUE TITLE
Insufficient Lamports

### ISSUE THREAD

**Issue by dant89** [kevinfaveri/solana-candy-factory#63]
I've been using the devnet for smaller collections (10 items) which has worked fine, I'm now trying to initiate it with 1,234 items for a final pre launch test however I'm getting the following error:

```
    Program 11111111111111111111111111111111 invoke [1]
    Transfer: insufficient lamports 999990000, need 2065018080
    Program 11111111111111111111111111111111 failed: custom program error: 0x1
```

I can't seem to find that cause of this issue, any ideas please? Possibly it's just an issue with using larger sizes on devnet?

Trace:

```
Processing file: 0
initializing config
Transaction simulation failed: Error processing Instruction 0: custom program error: 0x1 
    Program 11111111111111111111111111111111 invoke [1]
    Transfer: insufficient lamports 999990000, need 2065018080
    Program 11111111111111111111111111111111 failed: custom program error: 0x1
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x1
    at Connection.sendEncodedTransaction (/....../metaplex-foundation/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:3553:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Connection.sendRawTransaction (/....../metaplex-foundation/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:3513:20)
    at async Object.sendAndConfirmRawTransaction (/....../metaplex-foundation/metaplex/js/node_modules/@solana/web3.js/src/util/send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (/....../metaplex-foundation/metaplex/js/node_modules/@project-serum/anchor/src/provider.ts:112:18)
    at async Object.rpc [as initializeConfig] (/....../metaplex-foundation/metaplex/js/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:19:23) {
```

**Comment by AnderUstarroz** [comment]
Have you verified the price is correct? 
```
node build/candy-machine-cli.js show \
    -e devnet \
    -k ~/.config/solana/devnet.json
```
I have seen [some weird behavior ](https://github.com/metaplex-foundation/metaplex/issues/941)when updating price on the Candy Machine.

**Comment by megababosser** [comment]
Good day. Looks like not enough sol in your wallet. In devnet you can airdrop it
