### ISSUE TITLE
Error: ENOENT: no such file or directory, open './.cache/devnet-temp'

### ISSUE THREAD

**Issue by paul-atx** [kevinfaveri/solana-candy-factory#64]
I'm having an issue getting this setup on Ubuntu. It looks like a file is missing. I tried creating an empty file and removing the check for the file but it creates errors for NEXT_PUBLIC_CANDY_MACHINE_CONFIG
```
$ node ./devtools/dev/setup-envs-dev.js
internal/fs/utils.js:314
    throw err;
    ^

Error: ENOENT: no such file or directory, open './.cache/devnet-temp'
    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
    at /home/ubuntu/solana-candy-factory/devtools/dev/setup-envs-dev.js:42:31
    at FSReqCallback.oncomplete (fs.js:180:23) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: './.cache/devnet-temp'
}
```

**Comment by tburnam** [comment]
This is what fixed the issue for me: In `setup-envs-dev.js`, at line 42, it has:

```js
const metaplexTempFile = fs.readFileSync('./.cache/devnet-temp');
```

which is missing the `.json` extension. Replace with:
```js
const metaplexTempFile = fs.readFileSync('./.cache/devnet-temp.json');
```
